import type { Pedido, Producto } from "../tipos";

/* Datos de demostración, para poder abrir las pantallas sin conexión a la base.
   Son inventados a propósito y la pantalla lo dice: nunca se mezclan con los
   reales, porque un socio que vea 47 artículos que no existen podría intentar
   venderlos. Se usan solo cuando falta la configuración o la base falla. */

export const PRODUCTOS_DEMO: readonly Producto[] = [
  {
    id: "demo-1",
    marcaId: "demo-marca",
    marca: "Marca de ejemplo",
    marcaGiro: "alimentos",
    marcaCiudadAlmacen: "Cusco",
    marcaCiudadPunto: "Lima",
    nombre: "Café en grano de altura",
    categoria: "Bebidas",
    emoji: "☕",
    descripcion: "Tostado medio, cosecha de este año. Se muele al momento.",
    recomendaciones: "Funciona bien por kilo en oficinas y cafeterías pequeñas.",
    tiempoPreparacion: "1 día",
    variantes: [
      { id: "demo-1a", presentacion: "1 kg", precioPagina: 80, stockAlmacen: 12, stockPunto: 4 },
      { id: "demo-1b", presentacion: "500 g", precioPagina: 45, stockAlmacen: 7, stockPunto: 2 },
    ],
  },
  {
    id: "demo-2",
    marcaId: "demo-marca",
    marca: "Marca de ejemplo",
    marcaGiro: "alimentos",
    marcaCiudadAlmacen: "Cusco",
    marcaCiudadPunto: "Lima",
    nombre: "Cacao orgánico en polvo",
    categoria: "Bebidas",
    emoji: "🍫",
    descripcion: "Sin azúcar añadida, molienda fina.",
    recomendaciones: "Se vende solo en repostería casera.",
    tiempoPreparacion: "1 día",
    variantes: [{ id: "demo-2a", presentacion: "500 g", precioPagina: 45, stockAlmacen: 9, stockPunto: 0 }],
  },
  {
    id: "demo-3",
    marcaId: "demo-marca",
    marca: "Marca de ejemplo",
    marcaGiro: "alimentos",
    marcaCiudadAlmacen: "Cusco",
    marcaCiudadPunto: "Lima",
    nombre: "Miel de abeja de eucalipto",
    categoria: "Despensa",
    emoji: "🍯",
    descripcion: "De apicultores del valle, envasada en frasco de vidrio.",
    recomendaciones: "Sube bien en campañas de invierno.",
    tiempoPreparacion: "2 días",
    variantes: [{ id: "demo-3a", presentacion: "250 g", precioPagina: 30, stockAlmacen: 0, stockPunto: 0 }],
  },
  {
    id: "demo-4",
    marcaId: "demo-marca",
    marca: "Marca de ejemplo",
    marcaGiro: "alimentos",
    marcaCiudadAlmacen: "Cusco",
    marcaCiudadPunto: "Lima",
    nombre: "Aceite de oliva extra virgen",
    categoria: "Despensa",
    emoji: "🫒",
    descripcion: "Primera prensada en frío.",
    recomendaciones: "Buen acompañante del café en pedidos grandes.",
    tiempoPreparacion: "1 día",
    variantes: [{ id: "demo-4a", presentacion: "1 L", precioPagina: 22, stockAlmacen: 30, stockPunto: 11 }],
  },
  {
    id: "demo-5",
    marcaId: "demo-marca",
    marca: "Marca de ejemplo",
    marcaGiro: "alimentos",
    marcaCiudadAlmacen: "Cusco",
    marcaCiudadPunto: "Lima",
    nombre: "Quinua blanca lavada",
    categoria: "Despensa",
    emoji: "🌾",
    descripcion: "Lista para cocinar, sin saponina.",
    recomendaciones: "Pedido recurrente en menús semanales.",
    tiempoPreparacion: "1 día",
    variantes: [{ id: "demo-5a", presentacion: "500 g", precioPagina: 18, stockAlmacen: null, stockPunto: null }],
  },
  {
    id: "demo-6",
    marcaId: "demo-marca",
    marca: "Marca de ejemplo",
    marcaGiro: "alimentos",
    marcaCiudadAlmacen: "Cusco",
    marcaCiudadPunto: "Lima",
    nombre: "Panela granulada",
    categoria: "Despensa",
    emoji: "🧂",
    descripcion: "Caña sin refinar, endulzante natural.",
    recomendaciones: "Se vende junto con el café.",
    tiempoPreparacion: "1 día",
    variantes: [{ id: "demo-6a", presentacion: "1 kg", precioPagina: 15, stockAlmacen: 24, stockPunto: 6 }],
  },
];

export const PEDIDOS_DEMO: readonly Pedido[] = [
  {
    codigo: "SOC-0921-A1",
    estado: "pagado",
    destinatario: "Rosa Quispe",
    detalleEntrega: "Olva Courier · Miraflores",
    fecha: "21 set",
    numeroGuia: "",
    total: 80,
    ganancia: 12.8,
  },
  {
    codigo: "SOC-0920-B7",
    estado: "en_camino",
    destinatario: "Luis Ramos",
    detalleEntrega: "Shalom · Arequipa",
    fecha: "20 set",
    numeroGuia: "OLV-884213",
    total: 125,
    ganancia: 20,
  },
  {
    codigo: "SOC-0918-C3",
    estado: "entregado",
    destinatario: "Marina Flores",
    detalleEntrega: "Domicilio · San Isidro",
    fecha: "18 set",
    numeroGuia: "OLV-871004",
    total: 45,
    ganancia: 7.2,
  },
];
